# Generated by Django 5.1.2 on 2024-10-19 04:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_category_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='resume'),
        ),
    ]
