# Generated by Django 5.1.2 on 2024-10-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image_url',
        ),
    ]
