# Generated by Django 5.1.2 on 2024-10-23 06:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='resume'),
        ),
    ]
